### ISSUE TITLE
How did you create this list?

### ISSUE THREAD

**Issue by tkon99** [Tobiaqs/MagisterSchools#1]
Silly question maybe, but how did you put this list of schools together?

**Comment by Tobiaqs** [comment]
Eerst: https://selfservice.entree.kennisnet.nl/accountbeheer/
Haal uit de HTML de “rid” uit met Regex: `rid=([^"]+)`
De HTML bevat een meta-redirect, dus je kan het niet in browser doen tenzij je view-source: voor de URL zet.

Daarna: https://aselect.entree.kennisnet.nl/openaselect/sso/web?asid=<rid>
Haal hier alle scholen uit met Regex: `<option value="([^;]+);[^"]+">(.+?)</option>`

**Comment by tkon99** [comment]
Dacht al dat jullie het anders hadden gedaan:
Tip: https://mijn.magister.net/api/schools?filter=
(Minimaal 3 letters nodig)

Is misschien handig voor in jullie app.

**Comment by lieuwex** [comment]
> Haal uit de HTML de “rid” uit met Regex: rid=([^"]+)

http://stackoverflow.com/a/1732454/3142952

**Comment by Tobiaqs** [comment]
De Regex-gebaseerde code is bedoeld voor het tot op zekere hoogte handmatig ophalen van de lijst en is niet in de app ingebouwd. We houden de lijst zelf bij omdat er sommige scholen staan vermeldt onder een naam die leerlingen niet herkennen en er gevallen zijn waarbij school in het Magister 5-adres afwijkt van die in het Magister 6-adres.

Regex op zich in de eerste situatie beter dan een XML parser i.c.m. Regex. Bij het converteren van de lijst met scholen zal een XML parser misschien beter zijn, maar opnieuw, het is slechts voor het ophalen van een basislijst.

De genoemde API kende ik al, deze bemoeilijkt echter de handmatige aanpassingen.

**Comment by lieuwex** [comment]
> We houden de lijst zelf bij omdat er sommige scholen staan vermeldt onder een naam die leerlingen niet herkennen en er gevallen zijn waarbij school in het Magister 5-adres afwijkt van die in het Magister 6-adres.

Interessant, heb je voorbeelden van dit soort gevallen?

**Comment by Tobiaqs** [comment]
@thomasvt1 weet daar meer over.

**Comment by thomasvt1** [comment]
Het Koning Willem II College was bijvoorbeeld een school die niet in de lijst stond.

**Comment by lieuwex** [comment]
```
 $ curl -s "https://mijn.magister.net/api/schools?filter=koning" | jq "."
```

``` JSON
[
  {
    "Id": "9eafe861-cbd9-4068-9085-f6712ea48b0b",
    "Name": "Koning Willem II College",
    "Url": "https://willem2.magister.net"
  }
]
```

(Het zou wel problemen opleveren als iemand zoekt naar "Koning Willem 2". Ik bedenk me net dat het handig zou zijn om cijfers te strippen bij het zoeken naar scholen)

**Comment by Tobiaqs** [comment]
Ik heb deze API in overweging genomen. Het gebruik ervan zou de UX in ons geval verslechteren. Zoeken naar een school zou een query van drie karakters nodig hebben, en voor elke zoekopdracht is er een significante lag (in ieder geval op langzame mobiele verbindingen). Door de hele lijst in een keer op te halen hebben we geen lag zodra de lijst binnen is.

De API heeft ook een groot voordeel, namelijk dat deze waarschijnlijk zijn gegevens uit een complete database haalt.

Wat denkt @thomasvt1?

> (Het zou wel problemen opleveren als iemand zoekt naar "Koning Willem 2". Ik bedenk me net dat het handig zou zijn om cijfers te strippen bij het zoeken naar scholen)

`"Koning Willem 2".replace(/\d/g, "").trim();` ;)

**Comment by lieuwex** [comment]
Ik ben het gedeeltelijk eens met punt 1, ik zou de lijst eerder direct met een app meeleveren en dat dan icm met `mijn.magister.net` gebruiken zodat de lijst alleen functioneert als cache en `mijn.magister.net` gebruikt wordt om in de achtergrond meer scholen te laden. Zo heb je toch het beste van beide werelden.

> "Koning Willem 2".replace(/\d/g, "").trim(); ;)

Haha, dat klopt. Ik bedoelde dat ik het [hier](https://github.com/simplyGits/MagisterJS/blob/master/src/School.coffee#L44) tussen moet proppen :P. (ik zie wel of ik dat nog ga doen, we zijn van plan om een in ieder geval een groot gedeelte te herschrijven).
